from __future__ import annotations

import os
import platform
import shutil
import subprocess
import tempfile
from pathlib import Path

INSTALL_README = """\
# {name} MCP Server

Portable MCP proxy binary generated by [mcp-gen](https://github.com/mcp-factory/mcp-factory).

## Copy to target machine

Copy this entire directory to the machine where you want to run the MCP server.
The binary was built for **{target_triple}** — use the same OS and CPU architecture,
or rebuild with `mcp-gen package --target <triple>` on a machine with the Rust
cross-compilation toolchain installed.

## Configure upstream API

Edit `config.toml` or set environment variables:

| Variable | Description |
|----------|-------------|
| `MCP_FACTORY_BASE_URL` | Upstream API base URL (default from generation: `{base_url}`) |
| `MCP_FACTORY_BEARER_TOKEN` | Bearer auth token |
| `MCP_FACTORY_API_KEY` | API key (header mode) |
| `MCP_TRANSPORT` | `stdio`, `http`, or `both` (default: `{transport}`) |
| `MCP_FACTORY_BIND_ADDR` | HTTP bind address when using HTTP transport |

## Cursor MCP configuration

```json
{{
  "mcpServers": {{
    "{name}": {{
      "command": "/absolute/path/to/{name}/{binary_name}",
      "env": {{
        "MCP_FACTORY_BASE_URL": "{base_url}"
      }}
    }}
  }}
}}
```

## Run manually

```bash
./{binary_name}
```
"""


def target_triple(target: str | None) -> str:
    if target:
        return target
    arch = platform.machine()
    system = platform.system().lower()
    if system == "darwin":
        os_name = "macos"
    elif system == "linux":
        os_name = "linux"
    elif system == "windows":
        os_name = "windows"
    else:
        os_name = system
    return f"{arch}-{os_name}"


def release_binary_path(crate_dir: Path, crate_name: str, target: str | None) -> Path:
    binary_name = f"{crate_name}.exe" if platform.system() == "Windows" else crate_name
    if target:
        return crate_dir / "target" / target / "release" / binary_name
    return crate_dir / "target" / "release" / binary_name


def build_release(crate_dir: Path, *, target: str | None = None) -> None:
    cmd = ["cargo", "build", "--release", "--quiet"]
    if target:
        cmd.extend(["--target", target])
    env = os.environ.copy()
    env["CARGO_TARGET_DIR"] = str(crate_dir / "target")
    subprocess.run(cmd, cwd=crate_dir, check=True, env=env)


def assemble_dist(
    *,
    binary_path: Path,
    dist_dir: Path,
    crate_name: str,
    base_url: str,
    transport: str,
    target: str | None = None,
    config_path: Path | None = None,
) -> Path:
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    dist_dir.mkdir(parents=True)

    binary_name = binary_path.name
    shutil.copy2(binary_path, dist_dir / binary_name)
    os.chmod(dist_dir / binary_name, 0o755)

    if config_path and config_path.is_file():
        shutil.copy2(config_path, dist_dir / "config.toml")

    readme = INSTALL_README.format(
        name=crate_name,
        binary_name=binary_name,
        base_url=base_url,
        transport=transport,
        target_triple=target_triple(target),
    )
    (dist_dir / "README.txt").write_text(readme, encoding="utf-8")
    return dist_dir


def create_archive(dist_dir: Path) -> Path:
    archive_base = dist_dir.parent / dist_dir.name
    archive_path = shutil.make_archive(str(archive_base), "gztar", root_dir=dist_dir.parent, base_dir=dist_dir.name)
    return Path(archive_path)


def package_crate(
    crate_dir: Path,
    *,
    dist_dir: Path,
    crate_name: str,
    base_url: str,
    transport: str,
    target: str | None = None,
    archive: bool = False,
) -> tuple[Path, Path | None]:
    build_release(crate_dir, target=target)
    binary_path = release_binary_path(crate_dir, crate_name, target)
    if not binary_path.is_file():
        raise FileNotFoundError(f"expected release binary at {binary_path}")

    config_path = crate_dir / "config.toml"
    assembled = assemble_dist(
        binary_path=binary_path,
        dist_dir=dist_dir,
        crate_name=crate_name,
        base_url=base_url,
        transport=transport,
        target=target,
        config_path=config_path,
    )
    archive_path = create_archive(assembled) if archive else None
    return assembled, archive_path


def package_with_temp_crate(
    *,
    render_fn,
    dist_dir: Path,
    crate_name: str,
    base_url: str,
    transport: str,
    target: str | None = None,
    archive: bool = False,
    keep_source: bool = False,
) -> tuple[Path, Path | None, Path | None]:
    """Generate into a temp dir, build, and assemble a portable dist."""
    with tempfile.TemporaryDirectory(prefix="mcp-gen-") as tmp:
        crate_dir = Path(tmp) / crate_name
        render_fn(crate_dir)
        assembled, archive_path = package_crate(
            crate_dir,
            dist_dir=dist_dir,
            crate_name=crate_name,
            base_url=base_url,
            transport=transport,
            target=target,
            archive=archive,
        )
        source_dir = None
        if keep_source:
            source_dir = dist_dir.parent / f"{dist_dir.name}-source"
            if source_dir.exists():
                shutil.rmtree(source_dir)
            shutil.copytree(crate_dir, source_dir, ignore=shutil.ignore_patterns("target"))
        return assembled, archive_path, source_dir
